---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-prod
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./traefik-system/
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructures
