---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: metallb-values
    files:
      - values.yaml
