---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml
